version: '3.8'

services:

    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db

    #Database Service
    # db:
    #   image : mysql
    #   container_name : mysql
    #   volumes:
    #     - ./mysql/data:/var/lib/mysql
    #   ports:
    #     - "3306:3306"
    #   environment:
    #     MYSQL_DATABASE: blog
    #     MYSQL_ROOT_PASSWORD: password
    db:
        image: mysql
        container_name: mysql
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: w3cms3
            MYSQL_ROOT_PASSWORD: password

    # Application Service
    app:
        container_name: w3cms3
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www

    #phpMyAdmin Service
    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   container_name: phpmyadmin
    #   ports:
    #     - "3400:80"
    #   depends_on:
    #     - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "3400:80"
        depends_on:
            - db
